/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package infoh400_tp;

import com.pixelmed.dicom.AttributeList;
import com.pixelmed.dicom.AttributeTag;
import com.pixelmed.dicom.DicomDirectory;
import com.pixelmed.dicom.DicomDirectoryRecord;
import com.pixelmed.dicom.DicomException;
import com.pixelmed.dicom.DicomInputStream;
import com.pixelmed.dicom.TagFromName;
import com.pixelmed.display.SourceImage;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Administrateur
 */
public class MainWindow extends javax.swing.JFrame {
    
    private ArrayList<Patient> patients;
    private DefaultListModel<String> patientModel;
    private Database db;
    private String dicomDirPath;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        dicomDirPath = "";
        
        db = new Database();
        
        patients = PatientController.getAllPatients(db);
        patientModel = new DefaultListModel();
        patientList.setModel(patientModel);
        updatePatientModel();
    }
    
    private void updatePatientModel(){
        patientModel.clear();
        for(Patient p: patients){
            patientModel.addElement(p.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        addPatientButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientList = new javax.swing.JList<>();
        socialSecurity = new javax.swing.JTextField();
        dateOfBirth = new javax.swing.JTextField();
        editPatientButton = new javax.swing.JButton();
        deletePatientButton = new javax.swing.JButton();
        sendHL7Button = new javax.swing.JButton();
        hl7Host = new javax.swing.JTextField();
        hl7Port = new javax.swing.JTextField();
        openDICOMButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        dicomTree = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        dicomAttributes = new javax.swing.JTextPane();
        showImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstName.setToolTipText("first name");

        lastName.setToolTipText("last name");

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        addPatientButton.setText("Add");
        addPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientButtonActionPerformed(evt);
            }
        });

        patientList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                patientListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(patientList);

        socialSecurity.setToolTipText("social security");

        dateOfBirth.setToolTipText("date of birth");

        editPatientButton.setText("Edit");
        editPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPatientButtonActionPerformed(evt);
            }
        });

        deletePatientButton.setText("Delete");
        deletePatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePatientButtonActionPerformed(evt);
            }
        });

        sendHL7Button.setText("HL7 Send");
        sendHL7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendHL7ButtonActionPerformed(evt);
            }
        });

        hl7Host.setText("localhost");

        hl7Port.setText("52931");

        openDICOMButton.setText("Open DICOM");
        openDICOMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDICOMButtonActionPerformed(evt);
            }
        });

        dicomTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                dicomTreeValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(dicomTree);

        jScrollPane3.setViewportView(dicomAttributes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(openDICOMButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sendHL7Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hl7Host))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hl7Port, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(socialSecurity, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addPatientButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editPatientButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletePatientButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3)))
                .addGap(18, 18, 18)
                .addComponent(showImage, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPatientButton)
                    .addComponent(socialSecurity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editPatientButton)
                    .addComponent(deletePatientButton))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hl7Host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hl7Port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendHL7Button)))
                .addGap(33, 33, 33)
                .addComponent(openDICOMButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showImage, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientButtonActionPerformed
        Patient p = new Patient(socialSecurity.getText(), firstName.getText(), lastName.getText(), gender.getSelectedItem().toString(), dateOfBirth.getText());
        patients.add(p);
        PatientController.addPatient(db, p);
        updatePatientModel();
    }//GEN-LAST:event_addPatientButtonActionPerformed

    private void patientListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_patientListValueChanged
        int idx = patientList.getSelectedIndex();
        if( idx < 0 ) return;
        
        Patient pat = patients.get(idx);
        
        firstName.setText(pat.getPerson().getFirstName());
        lastName.setText(pat.getPerson().getLastName());
        if( pat.getPerson().getGender().equalsIgnoreCase("M"))
            gender.setSelectedIndex(0);
        else
            gender.setSelectedIndex(1);
        socialSecurity.setText(pat.getSocialSecurity());
        dateOfBirth.setText(pat.getPerson().getDateOfBirth());
    }//GEN-LAST:event_patientListValueChanged

    private void editPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPatientButtonActionPerformed
        int idx = patientList.getSelectedIndex();
        Patient pat = patients.get(idx);
        
        pat.setSocialSecurity(socialSecurity.getText());
        pat.getPerson().setFirstName(firstName.getText());
        pat.getPerson().setLastName(lastName.getText());
        pat.getPerson().setGender(gender.getSelectedItem().toString());
        pat.getPerson().setDateOfBirth(dateOfBirth.getText());
        
        PatientController.editPatient(db, pat);
        updatePatientModel();
    }//GEN-LAST:event_editPatientButtonActionPerformed

    private void deletePatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePatientButtonActionPerformed
        int idx = patientList.getSelectedIndex();
        Patient pat = patients.get(idx);
        
        PatientController.deletePatient(db, pat);
        patients.remove(pat);
        updatePatientModel();
    }//GEN-LAST:event_deletePatientButtonActionPerformed

    private void sendHL7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendHL7ButtonActionPerformed
        String host = hl7Host.getText();
        int port = Integer.valueOf(hl7Port.getText());
        
        int idx = patientList.getSelectedIndex();
        if( idx < 0 ) return;
        Patient pat = patients.get(idx);
        
        HL7 hl7 = new HL7(host, port);
        hl7.send_ADT_A01(pat);
    }//GEN-LAST:event_sendHL7ButtonActionPerformed

    private void openDICOMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDICOMButtonActionPerformed
        JFileChooser chooser = new JFileChooser("E:\\Dropbox\\ULB\\TPs\\2016-2017\\INFO-H-400\\Data\\DICOMDIR");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if( chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION ){
            File f = chooser.getSelectedFile();
            DicomDirectory dicomDir = DicomController.getDICOMDIR(f.getAbsolutePath());
            dicomTree.setModel(dicomDir);
        }
    }//GEN-LAST:event_openDICOMButtonActionPerformed

    private void dicomTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_dicomTreeValueChanged
        DicomController.selectDirectoryRecord(dicomTree);
        
        BufferedImage img = DicomController.getImageOrNull();
        if( img != null ) showImage.setIcon(new ImageIcon(img));
        
        String s = DicomController.getAttributesAsString();
        
        dicomAttributes.setText(s);
        dicomAttributes.setCaretPosition(0);
        
    }//GEN-LAST:event_dicomTreeValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatientButton;
    private javax.swing.JTextField dateOfBirth;
    private javax.swing.JButton deletePatientButton;
    private javax.swing.JTextPane dicomAttributes;
    private javax.swing.JTree dicomTree;
    private javax.swing.JButton editPatientButton;
    private javax.swing.JTextField firstName;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JTextField hl7Host;
    private javax.swing.JTextField hl7Port;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lastName;
    private javax.swing.JButton openDICOMButton;
    private javax.swing.JList<String> patientList;
    private javax.swing.JButton sendHL7Button;
    private javax.swing.JLabel showImage;
    private javax.swing.JTextField socialSecurity;
    // End of variables declaration//GEN-END:variables
}
