/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulb.lisa.lhist.view;

import java.awt.Image;
import java.io.File;
import ulb.lisa.lhist.controller.UserController;
import ulb.lisa.lhist.controller.HL7Client;
import ulb.lisa.lhist.controller.PatientController;
import ulb.lisa.lhist.model.Person;
import ulb.lisa.lhist.model.Patient;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.tree.TreeModel;
import ulb.lisa.lhist.controller.BeIDController;
import ulb.lisa.lhist.controller.DicomController;

/**
 *
 * @author Adrien Foucart
 */
public class MainWindow extends javax.swing.JFrame {
    
    private ArrayList<Patient> patients;
    private DefaultListModel<String> patientModel;
    private JFileChooser fc;
    private TreeModel ddrModel;
    private String dicomDirPath = "";
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        fc = new JFileChooser("E:/Dropbox/ULB/TPs/INFOH400/Data/DICOMDIR");
        
        patients = PatientController.getAllPatients();
        patientModel = new DefaultListModel();
        patientList.setModel(patientModel);
        updatePatientModel();
    }
    
    private void updatePatientModel(){
        patientModel.clear();
        for(Patient p: patients){
            patientModel.addElement(p.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox(Person.Gender.values());
        addPatientButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientList = new javax.swing.JList<>();
        socialSecurity = new javax.swing.JTextField();
        dateOfBirth = new javax.swing.JTextField();
        editPatientButton = new javax.swing.JButton();
        deletePatientButton = new javax.swing.JButton();
        idPicture = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        isAuthenticated = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        authenticateButton = new javax.swing.JButton();
        admissionButton = new javax.swing.JButton();
        selectDicomdirButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        dicomTree = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        dicomText = new javax.swing.JTextPane();
        dicomImage = new javax.swing.JLabel();
        sendDicomButton = new javax.swing.JButton();
        dicom_host = new javax.swing.JTextField();
        dicom_calledAET = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dicom_port = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        eIDButton = new javax.swing.JButton();
        photoLabel = new javax.swing.JLabel();
        eIDAuthButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstName.setToolTipText("first name");
        firstName.setName(""); // NOI18N

        lastName.setToolTipText("last name");

        addPatientButton.setText("Add");
        addPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientButtonActionPerformed(evt);
            }
        });

        patientList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                patientListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(patientList);

        socialSecurity.setToolTipText("social security");

        dateOfBirth.setToolTipText("date of birth");

        editPatientButton.setText("Edit");
        editPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPatientButtonActionPerformed(evt);
            }
        });

        deletePatientButton.setText("Delete");
        deletePatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePatientButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Last Name");

        jLabel2.setText("First Name");

        jLabel3.setText("Gender");

        jLabel4.setText("Social Security");

        jLabel5.setText("Date of Birth");

        isAuthenticated.setText("User not authenticated");

        password.setText("***********");

        authenticateButton.setText("Authenticate");
        authenticateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authenticateButtonActionPerformed(evt);
            }
        });

        admissionButton.setText("Admission");
        admissionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admissionButtonActionPerformed(evt);
            }
        });

        selectDicomdirButton.setText("Select DICOMDIR");
        selectDicomdirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDicomdirButtonActionPerformed(evt);
            }
        });

        dicomTree.setModel(ddrModel);
        dicomTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                dicomTreeValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(dicomTree);

        jScrollPane3.setViewportView(dicomText);

        sendDicomButton.setText("Send DICOM");
        sendDicomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendDicomButtonActionPerformed(evt);
            }
        });

        dicom_host.setText("localhost");

        dicom_calledAET.setText("PACS");

        jLabel6.setText("@");

        dicom_port.setText("11112");

        jLabel7.setText(":");

        eIDButton.setText("Load from eID");
        eIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eIDButtonActionPerformed(evt);
            }
        });

        eIDAuthButton.setText("ID Authenticate");
        eIDAuthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eIDAuthButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(addPatientButton)
                                            .addComponent(jLabel2)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(16, 16, 16)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(editPatientButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(deletePatientButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(socialSecurity, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 54, Short.MAX_VALUE))
                                                .addComponent(lastName)
                                                .addComponent(firstName))
                                            .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(isAuthenticated, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(authenticateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eIDAuthButton)
                                .addGap(92, 92, 92)
                                .addComponent(eIDButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(admissionButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idPicture)
                        .addGap(106, 106, 106))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dicom_calledAET, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dicom_host, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dicom_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(selectDicomdirButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sendDicomButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dicomImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(photoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(idPicture))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(socialSecurity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(5, 5, 5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(addPatientButton)
                                .addComponent(editPatientButton)
                                .addComponent(deletePatientButton)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isAuthenticated)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authenticateButton)
                    .addComponent(admissionButton)
                    .addComponent(eIDButton)
                    .addComponent(eIDAuthButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(selectDicomdirButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dicomImage, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendDicomButton)
                    .addComponent(dicom_host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dicom_calledAET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(dicom_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_patientListValueChanged
        int idx = patientList.getSelectedIndex();
        if( idx < 0 ) return;
        
        Patient pat = patients.get(idx);
        fillPatientForm(pat);
    }//GEN-LAST:event_patientListValueChanged

    private void addPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientButtonActionPerformed
        PatientController.addPatient(socialSecurity.getText(), firstName.getText(), lastName.getText(), gender.getSelectedItem().toString(), dateOfBirth.getText());
        updatePatientModel();
    }//GEN-LAST:event_addPatientButtonActionPerformed

    private void editPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPatientButtonActionPerformed
        int idx = patientList.getSelectedIndex();
        if( idx < 0 ) return;
        
        Patient p = patients.get(idx);
        PatientController.editPatient(p, socialSecurity.getText(), firstName.getText(), lastName.getText(), gender.getSelectedItem().toString(), dateOfBirth.getText());
        updatePatientModel();
    }//GEN-LAST:event_editPatientButtonActionPerformed

    private void deletePatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePatientButtonActionPerformed
        int idx = patientList.getSelectedIndex();
        if( idx < 0 ) return;
        
        Patient p = patients.get(idx);
        PatientController.deletePatient(p);
        updatePatientModel();
    }//GEN-LAST:event_deletePatientButtonActionPerformed

    private void authenticateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authenticateButtonActionPerformed
        
        if(UserController.authenticate(username.getText(), String.valueOf(password.getPassword()))){
            isAuthenticated.setText("User: " + username.getText());
        }
        
        username.setText("");
        password.setText("11111111111");
        
    }//GEN-LAST:event_authenticateButtonActionPerformed

    private void admissionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admissionButtonActionPerformed
        int idx = patientList.getSelectedIndex();
        if( idx < 0 ) return;
        
        Patient p = patients.get(idx);
        HL7Client.send_ADT_A01(p);
    }//GEN-LAST:event_admissionButtonActionPerformed

    private void selectDicomdirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDicomdirButtonActionPerformed
        int returnValue = fc.showOpenDialog(null);
        
        if( returnValue == JFileChooser.APPROVE_OPTION ){
            File selectedFile = fc.getSelectedFile();
            dicomDirPath = selectedFile.getAbsolutePath();
            
            ddrModel = DicomController.getDICOMDIR(selectedFile);
            dicomTree.setModel(ddrModel);
        }
    }//GEN-LAST:event_selectDicomdirButtonActionPerformed

    private void dicomTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_dicomTreeValueChanged
        
        String attributes = DicomController.getAttributes(dicomTree.getLastSelectedPathComponent());
        dicomText.setText(attributes);
        
        Image img = DicomController.getImage(dicomTree.getLastSelectedPathComponent(), dicomDirPath);
        System.out.println(img);
        if( img != null ){
            ImageIcon icon = new ImageIcon(img);
            dicomImage.setIcon(icon);
        }
    }//GEN-LAST:event_dicomTreeValueChanged

    private void sendDicomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendDicomButtonActionPerformed
        DicomController.storeDICOM(dicomTree.getLastSelectedPathComponent(), dicomDirPath, dicom_host.getText(), Integer.valueOf(dicom_port.getText()), dicom_calledAET.getText());
    }//GEN-LAST:event_sendDicomButtonActionPerformed

    private void eIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eIDButtonActionPerformed
        Patient pat = BeIDController.readID();
        
        if(pat != null){
            fillPatientForm(pat);
            
            photoLabel.setIcon(new ImageIcon(BeIDController.photo));
        }
    }//GEN-LAST:event_eIDButtonActionPerformed

    private void fillPatientForm(Patient pat){
        firstName.setText(pat.getPerson().getFirstName());
        lastName.setText(pat.getPerson().getLastName());
        gender.setSelectedItem(Person.Gender.valueOf(pat.getPerson().getGender()));
        socialSecurity.setText(pat.getSocialSecurity());
        dateOfBirth.setText(pat.getPerson().getDateOfBirth());
    }
    
    private void eIDAuthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eIDAuthButtonActionPerformed
        JPanel pinPanel = new JPanel();
        JLabel pinLabel = new JLabel("Enter PIN code");
        JPasswordField pinCodeField = new JPasswordField(4);
        pinPanel.add(pinLabel);
        pinPanel.add(pinCodeField);
        String[] options = new String[]{"OK", "Cancel"};
        
        int option = JOptionPane.showOptionDialog(null, pinPanel, "PIN Challenge", JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[1]);
        
        if( option == 0 ){
            String user = BeIDController.authenticate(new String(pinCodeField.getPassword()));
            if( user != null ){
                isAuthenticated.setText("eID = " + user);
            }
            else {
                isAuthenticated.setText("eID authentication failed");
            }
        }
        
    }//GEN-LAST:event_eIDAuthButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatientButton;
    private javax.swing.JButton admissionButton;
    private javax.swing.JButton authenticateButton;
    private javax.swing.JTextField dateOfBirth;
    private javax.swing.JButton deletePatientButton;
    private javax.swing.JLabel dicomImage;
    private javax.swing.JTextPane dicomText;
    private javax.swing.JTree dicomTree;
    private javax.swing.JTextField dicom_calledAET;
    private javax.swing.JTextField dicom_host;
    private javax.swing.JTextField dicom_port;
    private javax.swing.JButton eIDAuthButton;
    private javax.swing.JButton eIDButton;
    private javax.swing.JButton editPatientButton;
    private javax.swing.JTextField firstName;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel idPicture;
    private javax.swing.JLabel isAuthenticated;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lastName;
    private javax.swing.JPasswordField password;
    private javax.swing.JList<String> patientList;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JButton selectDicomdirButton;
    private javax.swing.JButton sendDicomButton;
    private javax.swing.JTextField socialSecurity;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
